### ISSUE TITLE
Support bitwise operators for Enum types

### ISSUE THREAD

**Issue by mwpowellhtx** [RupertAvery/csharpeval#2]
For bitwise operators supporting ordinal types like int and long, as well as FlagsAttribute decorated enums.

**Comment by RupertAvery** [comment]
I will look into this. Thanks!

**Comment by mwpowellhtx** [comment]
Verified for ordinal types it is just fine. However, for Flags decorated enum, not so much.

```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The binary operator And is not defined for the types 'Evaluate.CSharpEval.Console.Program+Types' and 'Evaluate.CSharpEval.Console.Program+Types'.
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
       at System.Linq.Expressions.Expression.And(Expression left, Expression right, MethodInfo method)
       at System.Linq.Expressions.Expression.And(Expression left, Expression right)
       at ExpressionEvaluator.Parser.ExpressionHelper.GetBinaryOperator(Expression le, Expression re, ExpressionType expressionType)
       at ExpressionEvaluator.Parser.ExpressionHelper.BinaryOperator(Expression le, Expression re, ExpressionType expressionType)
       at ExpressionEvaluator.Parser.ExprEvalParser.and_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.exclusive_or_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.inclusive_or_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.conditional_and_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.conditional_or_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.null_coalescing_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.conditional_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.non_assignment_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.paren_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.primary_expression_start()
       at ExpressionEvaluator.Parser.ExprEvalParser.primary_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.primary_or_array_creation_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.unary_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.multiplicative_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.additive_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.shift_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.relational_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.equality_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.and_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.exclusive_or_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.inclusive_or_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.conditional_and_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.conditional_or_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.null_coalescing_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.conditional_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.non_assignment_expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.expression()
       at ExpressionEvaluator.Parser.ExprEvalParser.single_expression()
       at ExpressionEvaluator.Parser.AntlrParser.Parse(Expression scope, Boolean isCall)
       at ExpressionEvaluator.ExpressionCompiler.BuildTree(Expression scopeParam, Boolean isCall)
       at ExpressionEvaluator.CompiledExpression`1.CompileWithScope[T,TScope](Boolean asCall)
       at ExpressionEvaluator.CompiledExpression`1.ScopeCompile[TScope]()
       at Evaluate.CSharpEval.Console.Program.ExtensibleTypeRegistryExampleNine() in i:\Source\Spikes\ExpressionEvaluators\src\Evaluate.CSharpEval.Console\Program.cs:line 192
       at Evaluate.CSharpEval.Console.Program.Main(String[] args) in i:\Source\Spikes\ExpressionEvaluators\src\Evaluate.CSharpEval.Console\Program.cs:line 225
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

Test code snippets:

```C#
[Flags]
private enum Types : int
{
    Fruit = 0x1,
    Grain = 0x2,
    Meat = 0x4,
    Dairy = 0x8
}
```

```C#
const Types all = Types.Fruit | Types.Grain | Types.Meat | Types.Dairy;
const Types some = Types.Meat | Types.Dairy;

var registry = new TypeRegistry();

registry.RegisterSymbol(@"all", all);
registry.RegisterSymbol(@"some", some);

var ce = new CompiledExpression<bool>(@"(all & some) == some")
{
    TypeRegistry = registry
};

var result = ce.ScopeCompile<Types>();

Debug.Assert(result(some));
```

**Comment by RupertAvery** [comment]
It appears that bitwise operators for Enum types in general are not supported.

**Comment by mwpowellhtx** [comment]
I reported as much. Would it be difficult to support that? Thanks...

**Comment by mwpowellhtx** [comment]
I did some research on it and it seems like an easy enough thing to detect if FlagsAttribute is present, then to convert the enum value to a UInt64 and do the [operation(s)](http://msdn.microsoft.com/en-us/library/6a71f45d.aspx) that way. In and of itself it is straightforward enough:. Not sure how that would work in this code base, though.

**Comment by RupertAvery** [comment]
Well, i couldn't find anything in the C# specification about
FlagsAttribute. Or that enums should be specifically converted to their
underlying type. What I did was to check if a type derived from Enum and
convert it accordingly before applying a binary operator. It works well
enough.

**Comment by mwpowellhtx** [comment]
I looked up on Google, those were a couple of the recommended approaches. At any rate, sounds great. I look forward to verifying the results.

**Comment by RupertAvery** [comment]
The latest commit should have those changes in place

**Comment by RupertAvery** [comment]
I should probably warn you that i made some file structure changes. If you
have any important changes it might make sense to clone to a new folder and
move your changes in

**Comment by mwpowellhtx** [comment]
No worries. Thanks for the heads up. I appreciate you looking into it.

**Comment by mwpowellhtx** [comment]
Just for my head knowledge, the changes are pushed to the repo? They don't
appear to be, the latest changes show a day ago, parsing neg numbers. Just
FYI.

**Comment by RupertAvery** [comment]
Sorry about that, I thought I pushed it!

**Comment by mwpowellhtx** [comment]
Remember you're working on an AntlParser branch instead of master. :)

**Comment by RupertAvery** [comment]
No, I did push it :) The full changelog is 

```
Fixed parsing of negative numbers

Fixed binary operators for Enum types
Added simple check for boxing conversion of value types to object type (Fixes method resolution for valuetype to object types)
Fixed some dynamic type checking
```

**Comment by mwpowellhtx** [comment]
Didn't see the rest. Thanks for clarifying. So there's likely to be a nuget package?

On July 23, 2015 9:29:58 PM EDT, David Khristepher Santos <notifications@github.com> wrote:
>No, I did push it :) The full changelog is 
>
>```
>Fixed parsing of negative numbers
>
>Fixed binary operators for Enum types
>Added simple check for boxing conversion of value types to object type
>(Fixes method resolution for valuetype to object types)
>Fixed some dynamic type checking
>```
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RupertAvery/csharpeval/issues/2#issuecomment-124288034

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
