### ISSUE TITLE
GenerateLamba throws ArgumentException

### ISSUE THREAD

**Issue by mwpowellhtx** [RupertAvery/csharpeval#3]
Consider where a simple TestData class exposes a Value property, and a ThisDynamic dynamic version of itself.

This seems to work:

```C#
var data = new TestData { Value = 42 };
var registry = new TypeRegistry {{@"data", data}};
var ce = new CompiledExpression<bool>(@"data.ThisDynamic.Value == 42") {TypeRegistry = registry};
Debug.Assert(ce.Eval());
```

However, in my case, I want to generate the lambda from the expression and assign it to the intended delegate variable.

```C#
var data = new TestData { Value = 42 };
var registry = new TypeRegistry {{@"self", data.ThisDynamic}};
var ce = new CompiledExpression<bool>(@"Value == 42") {TypeRegistry = registry};
// TODO: throw exception...
data.IsMatchFunction = ce.GenerateLambda<TestDataMatchDelegate, dynamic>(true, true).Compile();
Debug.Assert(data.IsMatch());
```

Other than that, it seems like the usual access modifier principles still apply? i.e. properties need to be public, or at least internal with InternalsVisibleTo the target assembly?

Thanks...

**Comment by mwpowellhtx** [comment]
Here's the exception details:

```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Expression of type 'System.Object' cannot be used for return type 'System.Boolean'
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
       at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
       at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
       at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
       at ExpressionEvaluator.CompiledExpression`1.GenerateLambda[T,TParam](Boolean withScope, Boolean asCall)
       at Evaluate.CSharpEval.Console.Program.WorkingExampleTwo() in i:\Source\Spikes\ExpressionEvaluators\src\Evaluate.CSharpEval.Console\Program.cs:line 35
       at Evaluate.CSharpEval.Console.Program.Main(String[] args) in i:\Source\Spikes\ExpressionEvaluators\src\Evaluate.CSharpEval.Console\Program.cs:line 43
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by mwpowellhtx** [comment]
Also, it's curious, this threw an exception first time around, but I tried to rerun and repeat it, and it seemed to "work", at least did not throw. Curious...

```C#
const int expected = 42;
var data = new TestData { Value = expected };
var registry = new TypeRegistry
{
    {@"data", data},
    {@"expected", expected}
};
var ce = new CompiledExpression<bool>(@"data.ThisDynamic.Value == expected") { TypeRegistry = registry };
Debug.Assert(ce.Eval());
```

Something to do with some caching and/or const-ness of type registry objects?
