### ISSUE TITLE
String.Join throws NullReferenceException

### ISSUE THREAD

**Issue by Tiliavir** [RupertAvery/csharpeval#5]
I just wrote a small unit test in your UnitTest.cs:

    [TestMethod]
    public void StringJoin()
    {
      var str = "String.Join(\",\", new[]{1, 2, 3, 4})";
      var c = new CompiledExpression(str) {TypeRegistry = new TypeRegistry()};
      var ret = c.Eval();
      Assert.AreEqual(ret, "1,2,3,4");
    }

unfortunately this throws a null reference exception. Any idea how to fix that or why that happens?

> Test Name:	StringJoin
Test FullName:	ExpressionEvaluator.Tests.UnitTest.StringJoin
Test Source:	C:\Git\csharpeval\TestProject1\UnitTest.cs : line 45
Test Outcome:	Failed
Test Duration:	0:00:00.0055511

> Result StackTrace:	
at ExpressionEvaluator.Parser.MethodResolution.IsApplicableFunctionMember(MethodInfo F, IEnumerable`1 argList) in C:\Git\csharpeval\Parser\MethodResolution.cs:line 356
   at ExpressionEvaluator.Parser.MethodResolution.GetApplicableMembers(Type type, TypeOrGeneric M, IEnumerable`1 A) in C:\Git\csharpeval\Parser\MethodResolution.cs:line 776
   at ExpressionEvaluator.Parser.ExpressionHelper.MethodInvokeExpression(Type type, Expression instance, TypeOrGeneric member, IEnumerable`1 args) in C:\Git\csharpeval\Parser\ExpressionHelper.cs:line 434
   at ExpressionEvaluator.Parser.ExpressionHelper.GetMethod(Expression le, TypeOrGeneric member, IEnumerable`1 args, Boolean isCall) in C:\Git\csharpeval\Parser\ExpressionHelper.cs:line 409
   at ExpressionEvaluator.Parser.ExprEvalParser.GetPrimaryExpressionPart(PrimaryExpressionPart primary_expression_part2, ITokenStream input, Expression value, Boolean throwsException) in C:\Git\csharpeval\Parser\ExprEval.g3.parser.cs:line 76
   at ExpressionEvaluator.Parser.ExprEvalParser.primary_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 3764
   at ExpressionEvaluator.Parser.ExprEvalParser.primary_or_array_creation_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 6910
   at ExpressionEvaluator.Parser.ExprEvalParser.unary_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 13162
   at ExpressionEvaluator.Parser.ExprEvalParser.multiplicative_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 13943
   at ExpressionEvaluator.Parser.ExprEvalParser.additive_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14071
   at ExpressionEvaluator.Parser.ExprEvalParser.shift_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14198
   at ExpressionEvaluator.Parser.ExprEvalParser.relational_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14325
   at ExpressionEvaluator.Parser.ExprEvalParser.equality_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14454
   at ExpressionEvaluator.Parser.ExprEvalParser.and_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14580
   at ExpressionEvaluator.Parser.ExprEvalParser.exclusive_or_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14688
   at ExpressionEvaluator.Parser.ExprEvalParser.inclusive_or_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14796
   at ExpressionEvaluator.Parser.ExprEvalParser.conditional_and_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14904
   at ExpressionEvaluator.Parser.ExprEvalParser.conditional_or_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 15012
   at ExpressionEvaluator.Parser.ExprEvalParser.null_coalescing_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 15120
   at ExpressionEvaluator.Parser.ExprEvalParser.conditional_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 15229
   at ExpressionEvaluator.Parser.ExprEvalParser.non_assignment_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 13884
   at ExpressionEvaluator.Parser.ExprEvalParser.expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 12725
   at ExpressionEvaluator.Parser.ExprEvalParser.single_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 11936
   at ExpressionEvaluator.Parser.AntlrParser.Parse(Expression scope, Boolean isCall) in C:\Git\csharpeval\Parser\AntlrParser.cs:line 51
   at ExpressionEvaluator.ExpressionCompiler.BuildTree(Expression scopeParam, Boolean isCall) in C:\Git\csharpeval\ExpressionCompiler.cs:line 38
   at ExpressionEvaluator.CompiledExpression`1.Compile() in C:\Git\csharpeval\CompiledExpression.cs:line 27
   at ExpressionEvaluator.CompiledExpression`1.Eval() in C:\Git\csharpeval\CompiledExpression.cs:line 122
   at ExpressionEvaluator.Tests.UnitTest.StringJoin() in C:\Git\csharpeval\TestProject1\UnitTest.cs:line 48
Result Message:	
Test method ExpressionEvaluator.Tests.UnitTest.StringJoin threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by RupertAvery** [comment]
Hi Markus,

Object array instantiation (the *new[]{1, 2, 3, 4}*) is not currently
supported, and is not being parsed correctly, resulting in a null
expression.

I will add this as an issue for tracking.

On Sun, Jul 19, 2015 at 9:18 PM, Markus Lindenmann <notifications@github.com
