### ISSUE TITLE
Double not parsed correctly

### ISSUE THREAD

**Issue by Tiliavir** [RupertAvery/csharpeval#6]
(*) sorry: I just realized, that I added an issue for this on CodePlex - so this is a duplicated!

Following test (added to UnitTest.cs) is not working as expected

    [TestMethod]
    public void Double()
    {
      double d = 123456789012345;
      var str = d.ToString(CultureInfo.InvariantCulture);
      var c = new CompiledExpression(str) { TypeRegistry = new TypeRegistry() };
      var ret = c.Eval();
      Assert.AreEqual(d, ret, "Input: <{0}>", str);
    }

> Test Name:	Double
Test FullName:	ExpressionEvaluator.Tests.UnitTest.Double
Test Source:	C:\Git\csharpeval\TestProject1\UnitTest.cs : line 56
Test Outcome:	Failed
Test Duration:	0:00:00.1978558

> Result StackTrace:	
at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s, IFormatProvider provider)
   at ExpressionEvaluator.Parser.ExpressionHelper.ParseIntLiteral(String token) in C:\Git\csharpeval\Parser\ExpressionHelper.cs:line 756
   at ExpressionEvaluator.Parser.ExprEvalParser.literal() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 34115
   at ExpressionEvaluator.Parser.ExprEvalParser.primary_expression_start() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 4621
   at ExpressionEvaluator.Parser.ExprEvalParser.primary_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 3482
   at ExpressionEvaluator.Parser.ExprEvalParser.primary_or_array_creation_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 6910
   at ExpressionEvaluator.Parser.ExprEvalParser.unary_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 13162
   at ExpressionEvaluator.Parser.ExprEvalParser.multiplicative_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 13943
   at ExpressionEvaluator.Parser.ExprEvalParser.additive_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14071
   at ExpressionEvaluator.Parser.ExprEvalParser.shift_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14198
   at ExpressionEvaluator.Parser.ExprEvalParser.relational_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14325
   at ExpressionEvaluator.Parser.ExprEvalParser.equality_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14454
   at ExpressionEvaluator.Parser.ExprEvalParser.and_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14580
   at ExpressionEvaluator.Parser.ExprEvalParser.exclusive_or_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14688
   at ExpressionEvaluator.Parser.ExprEvalParser.inclusive_or_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14796
   at ExpressionEvaluator.Parser.ExprEvalParser.conditional_and_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 14904
   at ExpressionEvaluator.Parser.ExprEvalParser.conditional_or_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 15012
   at ExpressionEvaluator.Parser.ExprEvalParser.null_coalescing_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 15120
   at ExpressionEvaluator.Parser.ExprEvalParser.conditional_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 15229
   at ExpressionEvaluator.Parser.ExprEvalParser.non_assignment_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 13884
   at ExpressionEvaluator.Parser.ExprEvalParser.expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 12725
   at ExpressionEvaluator.Parser.ExprEvalParser.single_expression() in C:\Git\csharpeval\obj\Debug\ExprEvalParser.cs:line 11936
   at ExpressionEvaluator.Parser.AntlrParser.Parse(Expression scope, Boolean isCall) in C:\Git\csharpeval\Parser\AntlrParser.cs:line 51
   at ExpressionEvaluator.ExpressionCompiler.BuildTree(Expression scopeParam, Boolean isCall) in C:\Git\csharpeval\ExpressionCompiler.cs:line 38
   at ExpressionEvaluator.CompiledExpression`1.Compile() in C:\Git\csharpeval\CompiledExpression.cs:line 27
   at ExpressionEvaluator.CompiledExpression`1.Eval() in C:\Git\csharpeval\CompiledExpression.cs:line 122
   at ExpressionEvaluator.Tests.UnitTest.Double() in C:\Git\csharpeval\TestProject1\UnitTest.cs:line 60
Result Message:	
Test method ExpressionEvaluator.Tests.UnitTest.Double threw exception: 
System.OverflowException: Value was either too large or too small for an Int32.

**Comment by RupertAvery** [comment]
You are coercing what is basically an Int64 literal into a double, converting it into a string, which removes all context of it being a double, then parsing it as an Int64. So technically this should be, Int64 literal not parsed correctly.
